# Generated by Django 5.2.5 on 2025-08-31 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SleepGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_hours",
                    models.DecimalField(decimal_places=2, default=8, max_digits=4),
                ),
                ("target_bedtime", models.TimeField(blank=True, null=True)),
                ("target_waketime", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sleep_goal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SleepSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "quality",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="1 (poor) to 5 (excellent)"
                    ),
                ),
                (
                    "latency_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Time to fall asleep"
                    ),
                ),
                ("awakenings", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags like 'caffeine, workout'",
                        max_length=200,
                    ),
                ),
                (
                    "stages_json",
                    models.JSONField(
                        blank=True,
                        help_text="Optional list of dicts with 't' and 'stage'",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sleep_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start"],
            },
        ),
    ]
