# Generated by Django 5.2.5 on 2025-08-31 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleep", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sleepgoal",
            name="target_bedtime",
            field=models.TimeField(
                blank=True, help_text="Desired bedtime (optional)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sleepgoal",
            name="target_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                help_text="Target sleep duration in hours (e.g., 8.00)",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="sleepgoal",
            name="target_waketime",
            field=models.TimeField(
                blank=True, help_text="Desired waketime (optional)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sleepsession",
            name="awakenings",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of awakenings"
            ),
        ),
        migrations.AlterField(
            model_name="sleepsession",
            name="end",
            field=models.DateTimeField(help_text="End time of the sleep session"),
        ),
        migrations.AlterField(
            model_name="sleepsession",
            name="latency_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="Time to fall asleep in minutes"
            ),
        ),
        migrations.AlterField(
            model_name="sleepsession",
            name="stages_json",
            field=models.JSONField(
                blank=True,
                help_text="Optional list of dicts with 't' (timestamp) and 'stage' (e.g., [{'t': '09:00', 'stage': 'light'}])",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sleepsession",
            name="start",
            field=models.DateTimeField(help_text="Start time of the sleep session"),
        ),
        migrations.AddIndex(
            model_name="sleepgoal",
            index=models.Index(fields=["user"], name="sleep_goal_user_idx"),
        ),
        migrations.AddIndex(
            model_name="sleepsession",
            index=models.Index(
                fields=["user", "start"], name="sleep_session_user_start_idx"
            ),
        ),
    ]
